#define APP_NAME "noisegen"
#define APP_VERSION "v1.0.0"

#define WINDOW_SIZE_X 1024
#define WINDOW_SIZE_Y 528
#define WINDOW_FPS 60

#define APP_NAME_LABEL_X 8
#define APP_NAME_LABEL_Y 8
#define APP_NAME_LABEL_W 128
#define APP_NAME_LABEL_H 16

#define TEX_BOX_X 504
#define TEX_BOX_Y 8
#define TEX_BOX_SIZE 512

#define TEX_START_RES_X 512
#define TEX_START_RES_Y 512
#define TEX_START_SEED 0
#define TEX_START_FREQ 1.0f
#define TEX_START_SEAMLESS 0
#define TEX_START_RANGE_MIN -1.0f
#define TEX_START_RANGE_MAX 1.0f

#define EXPORT_BTN_LABEL "EXPORT"
#define EXPORT_BTN_X 8
#define EXPORT_BTN_Y 36
#define EXPORT_BTN_W 96
#define EXPORT_BTN_H 24
#define EXPORT_FILENAME_LABEL "FILENAME:"
#define EXPORT_FILENAME_LABEL_X 112
#define EXPORT_FILENAME_LABEL_Y 40
#define EXPORT_FILENAME_LABEL_W 96
#define EXPORT_FILENAME_LABEL_H 16
#define EXPORT_FILENAME_MAX_SIZE 64
#define EXPORT_FILENAME_X 180
#define EXPORT_FILENAME_Y 36
#define EXPORT_FILENAME_W 160
#define EXPORT_FILENAME_H 24

#define EXPORT_MSGBOX_SUCCESS_TITLE "Export image"
#define EXPORT_MSGBOX_SUCCESS_MESSAGE "Image exported successfully."
#define EXPORT_MSGBOX_SUCCESS_BUTTONS "Ok"
#define EXPORT_MSGBOX_SUCCESS_W 224
#define EXPORT_MSGBOX_SUCCESS_H 96
#define EXPORT_MSGBOX_FAILURE_TITLE "Export image"
#define EXPORT_MSGBOX_FAILURE_MESSAGE "Exporting image failed."
#define EXPORT_MSGBOX_FAILURE_BUTTONS "Ok"
#define EXPORT_MSGBOX_FAILURE_W 224
#define EXPORT_MSGBOX_FAILURE_H 96

#define SEED_SELECTOR_LABEL "SEED:"
#define SEED_SELECTOR_LABEL_X 8
#define SEED_SELECTOR_LABEL_Y 92
#define SEED_SELECTOR_LABEL_W 32
#define SEED_SELECTOR_LABEL_H 16
#define SEED_SELECTOR_X 64
#define SEED_SELECTOR_Y 88
#define SEED_SELECTOR_W 96
#define SEED_SELECTOR_H 24
#define SEED_SELECTOR_MIN -999999
#define SEED_SELECTOR_MAX 999999

#define RES_SELECTOR_LABEL "RESOLUTION:"
#define RES_SELECTOR_LABEL_X 200
#define RES_SELECTOR_LABEL_Y 92
#define RES_SELECTOR_LABEL_W 96
#define RES_SELECTOR_LABEL_H 16
#define RES_SELECTOR_X_X 300
#define RES_SELECTOR_X_Y 88
#define RES_SELECTOR_Y_X 388
#define RES_SELECTOR_Y_Y 88
#define RES_SELECTOR_W 64
#define RES_SELECTOR_H 24
#define RES_SELECTOR_MIN 1
#define RES_SELECTOR_MAX 4096
#define RES_SELECTOR_X_LABEL "X "
#define RES_SELECTOR_Y_LABEL "Y "

#define FREQ_SELECTOR_LABEL "FREQUENCY:"
#define FREQ_SELECTOR_LABEL_X 8
#define FREQ_SELECTOR_LABEL_Y 124
#define FREQ_SELECTOR_LABEL_W 96
#define FREQ_SELECTOR_LABEL_H 16
#define FREQ_SELECTOR_X 100
#define FREQ_SELECTOR_Y 127
#define FREQ_SELECTOR_W 196
#define FREQ_SELECTOR_H 12
#define FREQ_SELECTOR_MIN 0.00001f
#define FREQ_SELECTOR_MAX 2.0f

#define SEAMLESS_SELECTOR_LABEL "SEAMLESS"
#define SEAMLESS_SELECTOR_X 350
#define SEAMLESS_SELECTOR_Y 127
#define SEAMLESS_SELECTOR_W 12
#define SEAMLESS_SELECTOR_H 12

#define RANGE_SELECTOR_LABEL "RANGE:"
#define RANGE_SELECTOR_LABEL_X 8
#define RANGE_SELECTOR_LABEL_Y 160
#define RANGE_SELECTOR_LABEL_W 96
#define RANGE_SELECTOR_LABEL_H 16
#define RANGE_SELECTOR_MIN_LABEL "MIN "
#define RANGE_SELECTOR_MIN_X 100
#define RANGE_SELECTOR_MIN_Y 163
#define RANGE_SELECTOR_MIN_W 128
#define RANGE_SELECTOR_MIN_H 12
#define RANGE_SELECTOR_MIN_MIN -1.0f
#define RANGE_SELECTOR_MIN_MAX 1.0f
#define RANGE_SELECTOR_MAX_LABEL " MAX"
#define RANGE_SELECTOR_MAX_X 316
#define RANGE_SELECTOR_MAX_Y 163
#define RANGE_SELECTOR_MAX_W 128
#define RANGE_SELECTOR_MAX_H 12
#define RANGE_SELECTOR_MAX_MIN -1.0f
#define RANGE_SELECTOR_MAX_MAX 1.0f
