#define APP_NAME "noisegen"
#define APP_VERSION "v1.0.0"

#define TEX_START_RES_X 512
#define TEX_START_RES_Y 512
#define TEX_START_SEED 0
#define TEX_START_FREQ 1.0f
#define TEX_START_SEAMLESS 0
#define TEX_START_RANGE_MIN -1.0f
#define TEX_START_RANGE_MAX 1.0f
#define TEX_START_POWER 1.0f
#define TEX_START_INVERT 0
#define TEX_START_OCTAVES 1
#define TEX_START_PERSISTENCE 0.5f
#define TEX_START_LACUNARITY 2.0f

#define WINDOW_SIZE_X 1024
#define WINDOW_SIZE_Y 528
#define WINDOW_FPS 60

#define PADDING 8
#define INPUT_START_X 124

#define LABEL_W 128
#define LABEL_H 16

#define V_SHORT_GAP 28
#define V_LONG_GAP 48
#define H_SHORT_GAP 20
#define H_MEDIUM_GAP 40
#define H_LONG_GAP 80
#define H_XLONG_GAP 90

#define SLIDER_LONG_W 180
#define SLIDER_SHORT_W 101
#define SLIDER_H 12
#define SLIDER_Y_DIFF 2

#define CHECKBOX_W 12
#define CHECKBOX_H 12
#define CHECKBOX_Y_DIFF 2

#define INPUTBOX_LONG_W 180
#define INPUTBOX_SHORT_W 80
#define INPUTBOX_H 20
#define INPUTBOX_Y_DIFF -2

#define BUTTON_W 96
#define BUTTON_H 24
#define BUTTON_Y_DIFF -4

#define MSGBOX_W 224
#define MSGBOX_H 96

#define TEX_BOX_X 504
#define TEX_BOX_Y 8
#define TEX_BOX_SIZE 512

#define APP_NAME_LABEL_X PADDING
#define APP_NAME_LABEL_Y PADDING
#define APP_NAME_LABEL_W LABEL_W
#define APP_NAME_LABEL_H LABEL_H

#define EXPORT_FILENAME_LABEL "FILENAME:"
#define EXPORT_FILENAME_START_VAL "noise.png"
#define EXPORT_FILENAME_LABEL_X PADDING
#define EXPORT_FILENAME_LABEL_Y APP_NAME_LABEL_Y + V_SHORT_GAP
#define EXPORT_FILENAME_LABEL_W LABEL_W
#define EXPORT_FILENAME_LABEL_H LABEL_H
#define EXPORT_FILENAME_MAX_SIZE 64
#define EXPORT_FILENAME_X INPUT_START_X
#define EXPORT_FILENAME_Y EXPORT_FILENAME_LABEL_Y + INPUTBOX_Y_DIFF
#define EXPORT_FILENAME_W INPUTBOX_LONG_W
#define EXPORT_FILENAME_H INPUTBOX_H

#define EXPORT_BTN_LABEL "EXPORT"
#define EXPORT_BTN_X EXPORT_FILENAME_X + EXPORT_FILENAME_W + H_MEDIUM_GAP
#define EXPORT_BTN_Y EXPORT_FILENAME_LABEL_Y + BUTTON_Y_DIFF
#define EXPORT_BTN_W BUTTON_W
#define EXPORT_BTN_H BUTTON_H

#define RES_SELECTOR_LABEL "RESOLUTION:"
#define RES_SELECTOR_LABEL_X PADDING
#define RES_SELECTOR_LABEL_Y EXPORT_BTN_Y + V_SHORT_GAP
#define RES_SELECTOR_LABEL_W LABEL_W
#define RES_SELECTOR_LABEL_H LABEL_H
#define RES_SELECTOR_W INPUTBOX_SHORT_W
#define RES_SELECTOR_H INPUTBOX_H
#define RES_SELECTOR_X_X INPUT_START_X
#define RES_SELECTOR_X_Y RES_SELECTOR_LABEL_Y + INPUTBOX_Y_DIFF
#define RES_SELECTOR_Y_X RES_SELECTOR_X_X + RES_SELECTOR_W + H_SHORT_GAP
#define RES_SELECTOR_Y_Y RES_SELECTOR_LABEL_Y + INPUTBOX_Y_DIFF
#define RES_SELECTOR_MIN 1
#define RES_SELECTOR_MAX 4096
#define RES_SELECTOR_X_LABEL "X "
#define RES_SELECTOR_Y_LABEL "Y "

#define EXPORT_MSGBOX_SUCCESS_TITLE "Export image"
#define EXPORT_MSGBOX_SUCCESS_MESSAGE "Image exported successfully."
#define EXPORT_MSGBOX_SUCCESS_BUTTONS "Ok"
#define EXPORT_MSGBOX_SUCCESS_W MSGBOX_W
#define EXPORT_MSGBOX_SUCCESS_H MSGBOX_H
#define EXPORT_MSGBOX_FAILURE_TITLE "Export image"
#define EXPORT_MSGBOX_FAILURE_MESSAGE "Exporting image failed."
#define EXPORT_MSGBOX_FAILURE_BUTTONS "Ok"
#define EXPORT_MSGBOX_FAILURE_W MSGBOX_W
#define EXPORT_MSGBOX_FAILURE_H MSGBOX_H

#define SEED_SELECTOR_LABEL "SEED:"
#define SEED_SELECTOR_LABEL_X PADDING
#define SEED_SELECTOR_LABEL_Y RES_SELECTOR_LABEL_Y + V_LONG_GAP
#define SEED_SELECTOR_LABEL_W LABEL_W
#define SEED_SELECTOR_LABEL_H LABEL_H
#define SEED_SELECTOR_X INPUT_START_X
#define SEED_SELECTOR_Y SEED_SELECTOR_LABEL_Y + INPUTBOX_Y_DIFF
#define SEED_SELECTOR_W INPUTBOX_LONG_W
#define SEED_SELECTOR_H INPUTBOX_H
#define SEED_SELECTOR_MIN -999999
#define SEED_SELECTOR_MAX 999999

#define FREQ_SELECTOR_LABEL "FREQUENCY:"
#define FREQ_SELECTOR_LABEL_LEFT "0.0"
#define FREQ_SELECTOR_LABEL_RIGHT "1.0"
#define FREQ_SELECTOR_LABEL_X PADDING
#define FREQ_SELECTOR_LABEL_Y SEED_SELECTOR_LABEL_Y + V_SHORT_GAP
#define FREQ_SELECTOR_LABEL_W LABEL_W
#define FREQ_SELECTOR_LABEL_H LABEL_H
#define FREQ_SELECTOR_X INPUT_START_X
#define FREQ_SELECTOR_Y FREQ_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define FREQ_SELECTOR_W SLIDER_LONG_W
#define FREQ_SELECTOR_H SLIDER_H
#define FREQ_SELECTOR_MIN 0.00001f
#define FREQ_SELECTOR_MAX 2.0f
#define FREQ_SELECTOR_VALUE_X FREQ_SELECTOR_X + FREQ_SELECTOR_W + H_MEDIUM_GAP
#define FREQ_SELECTOR_VALUE_Y FREQ_SELECTOR_LABEL_Y
#define FREQ_SELECTOR_VALUE_W LABEL_W
#define FREQ_SELECTOR_VALUE_H LABEL_H

#define SEAMLESS_SELECTOR_LABEL "SEAMLESS"
#define SEAMLESS_SELECTOR_X FREQ_SELECTOR_X + FREQ_SELECTOR_W + H_XLONG_GAP
#define SEAMLESS_SELECTOR_Y FREQ_SELECTOR_LABEL_Y + CHECKBOX_Y_DIFF
#define SEAMLESS_SELECTOR_W CHECKBOX_W
#define SEAMLESS_SELECTOR_H CHECKBOX_H

#define POWER_SELECTOR_LABEL "POWER:"
#define POWER_SELECTOR_LABEL_LEFT "1.0"
#define POWER_SELECTOR_LABEL_RIGHT "8.0"
#define POWER_SELECTOR_LABEL_X PADDING
#define POWER_SELECTOR_LABEL_Y FREQ_SELECTOR_LABEL_Y + V_SHORT_GAP
#define POWER_SELECTOR_LABEL_W LABEL_W
#define POWER_SELECTOR_LABEL_H LABEL_H
#define POWER_SELECTOR_X INPUT_START_X
#define POWER_SELECTOR_Y POWER_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define POWER_SELECTOR_W SLIDER_LONG_W
#define POWER_SELECTOR_H SLIDER_H
#define POWER_SELECTOR_MIN 1.0f
#define POWER_SELECTOR_MAX 8.0f
#define POWER_SELECTOR_VALUE_X                                                 \
    POWER_SELECTOR_X + POWER_SELECTOR_W + H_MEDIUM_GAP
#define POWER_SELECTOR_VALUE_Y POWER_SELECTOR_LABEL_Y
#define POWER_SELECTOR_VALUE_W LABEL_W
#define POWER_SELECTOR_VALUE_H LABEL_H

#define INVERT_SELECTOR_LABEL "INVERT"
#define INVERT_SELECTOR_X POWER_SELECTOR_X + POWER_SELECTOR_W + H_XLONG_GAP
#define INVERT_SELECTOR_Y POWER_SELECTOR_LABEL_Y + CHECKBOX_Y_DIFF
#define INVERT_SELECTOR_W CHECKBOX_W
#define INVERT_SELECTOR_H CHECKBOX_H

#define RANGE_SELECTOR_LABEL "RANGE:"
#define RANGE_SELECTOR_LABEL_X PADDING
#define RANGE_SELECTOR_LABEL_Y POWER_SELECTOR_LABEL_Y + V_SHORT_GAP
#define RANGE_SELECTOR_LABEL_W LABEL_W
#define RANGE_SELECTOR_LABEL_H LABEL_H
#define RANGE_SELECTOR_MIN_LABEL "MIN "
#define RANGE_SELECTOR_MIN_X INPUT_START_X
#define RANGE_SELECTOR_MIN_Y RANGE_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define RANGE_SELECTOR_MIN_W SLIDER_SHORT_W
#define RANGE_SELECTOR_MIN_H SLIDER_H
#define RANGE_SELECTOR_MIN_MIN -1.0f
#define RANGE_SELECTOR_MIN_MAX 1.0f
#define RANGE_SELECTOR_MAX_LABEL " MAX"
#define RANGE_SELECTOR_MAX_X                                                   \
    RANGE_SELECTOR_MIN_X + RANGE_SELECTOR_MIN_W + H_LONG_GAP
#define RANGE_SELECTOR_MAX_Y RANGE_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define RANGE_SELECTOR_MAX_W SLIDER_SHORT_W
#define RANGE_SELECTOR_MAX_H SLIDER_H
#define RANGE_SELECTOR_MAX_MIN -1.0f
#define RANGE_SELECTOR_MAX_MAX 1.0f

#define OCTAVES_SELECTOR_LABEL "OCTAVES:"
#define OCTAVES_SELECTOR_LABEL_LEFT "1"
#define OCTAVES_SELECTOR_LABEL_RIGHT "8"
#define OCTAVES_SELECTOR_LABEL_X PADDING
#define OCTAVES_SELECTOR_LABEL_Y RANGE_SELECTOR_LABEL_Y + V_LONG_GAP
#define OCTAVES_SELECTOR_LABEL_W LABEL_W
#define OCTAVES_SELECTOR_LABEL_H LABEL_H
#define OCTAVES_SELECTOR_X INPUT_START_X
#define OCTAVES_SELECTOR_Y OCTAVES_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define OCTAVES_SELECTOR_W SLIDER_LONG_W
#define OCTAVES_SELECTOR_H SLIDER_H
#define OCTAVES_SELECTOR_MIN 1.0f
#define OCTAVES_SELECTOR_MAX 8.0f
#define OCTAVES_SELECTOR_VALUE_X                                               \
    OCTAVES_SELECTOR_X + OCTAVES_SELECTOR_W + H_MEDIUM_GAP
#define OCTAVES_SELECTOR_VALUE_Y OCTAVES_SELECTOR_LABEL_Y
#define OCTAVES_SELECTOR_VALUE_W LABEL_W
#define OCTAVES_SELECTOR_VALUE_H LABEL_H

#define PERSISTENCE_SELECTOR_LABEL "PERSISTENCE:"
#define PERSISTENCE_SELECTOR_LABEL_LEFT "0.0"
#define PERSISTENCE_SELECTOR_LABEL_RIGHT "1.0"
#define PERSISTENCE_SELECTOR_LABEL_X PADDING
#define PERSISTENCE_SELECTOR_LABEL_Y OCTAVES_SELECTOR_LABEL_Y + V_SHORT_GAP
#define PERSISTENCE_SELECTOR_LABEL_W LABEL_W
#define PERSISTENCE_SELECTOR_LABEL_H LABEL_H
#define PERSISTENCE_SELECTOR_X INPUT_START_X
#define PERSISTENCE_SELECTOR_Y PERSISTENCE_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define PERSISTENCE_SELECTOR_W SLIDER_LONG_W
#define PERSISTENCE_SELECTOR_H SLIDER_H
#define PERSISTENCE_SELECTOR_MIN 0.0f
#define PERSISTENCE_SELECTOR_MAX 1.0f
#define PERSISTENCE_SELECTOR_VALUE_X                                           \
    PERSISTENCE_SELECTOR_X + PERSISTENCE_SELECTOR_W + H_MEDIUM_GAP
#define PERSISTENCE_SELECTOR_VALUE_Y PERSISTENCE_SELECTOR_LABEL_Y
#define PERSISTENCE_SELECTOR_VALUE_W LABEL_W
#define PERSISTENCE_SELECTOR_VALUE_H LABEL_H

#define LACUNARITY_SELECTOR_LABEL "LACUNARITY:"
#define LACUNARITY_SELECTOR_LABEL_LEFT "0.1"
#define LACUNARITY_SELECTOR_LABEL_RIGHT "4.0"
#define LACUNARITY_SELECTOR_LABEL_X PADDING
#define LACUNARITY_SELECTOR_LABEL_Y PERSISTENCE_SELECTOR_LABEL_Y + V_SHORT_GAP
#define LACUNARITY_SELECTOR_LABEL_W LABEL_W
#define LACUNARITY_SELECTOR_LABEL_H LABEL_H
#define LACUNARITY_SELECTOR_X INPUT_START_X
#define LACUNARITY_SELECTOR_Y LACUNARITY_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define LACUNARITY_SELECTOR_W SLIDER_LONG_W
#define LACUNARITY_SELECTOR_H SLIDER_H
#define LACUNARITY_SELECTOR_MIN 0.1f
#define LACUNARITY_SELECTOR_MAX 4.0f
#define LACUNARITY_SELECTOR_VALUE_X                                            \
    LACUNARITY_SELECTOR_X + LACUNARITY_SELECTOR_W + H_MEDIUM_GAP
#define LACUNARITY_SELECTOR_VALUE_Y LACUNARITY_SELECTOR_LABEL_Y
#define LACUNARITY_SELECTOR_VALUE_W LABEL_W
#define LACUNARITY_SELECTOR_VALUE_H LABEL_H
