#define APP_NAME "noisegen"
#define APP_VERSION "v1.0.0"

#define START_RES_X 512
#define START_RES_Y 512
#define START_NOISE_TYPE noise_type_opensimplex
#define START_MODE mode_one
#define START_SQUARED 0
#define START_SEED 0
#define START_FREQ 1.0f
#define START_JITTER 0.5f
#define START_SEAMLESS 0
#define START_RANGE_MIN -1.0f
#define START_RANGE_MAX 1.0f
#define START_POWER 1.0f
#define START_INVERT 0
#define START_OCTAVES 1
#define START_PERSISTENCE 0.5f
#define START_LACUNARITY 2.0f

#define WINDOW_SIZE_X 1024
#define WINDOW_SIZE_Y 528
#define WINDOW_FPS 60

#define TWO 2.0f
#define HALF 0.5f
#define TAU PI * 2.0f
#define RGBMAX 255
#define PADDING 8

#define INPUT_START_X 124

#define LABEL_W 128
#define LABEL_H 16

#define V_SHORT_GAP 28
#define V_LONG_GAP 48
#define H_SHORT_GAP 20
#define H_MEDIUM_GAP 40
#define H_LONG_GAP 80
#define H_XLONG_GAP 90

#define SLIDER_LONG_W 180
#define SLIDER_SHORT_W 101
#define SLIDER_H 12
#define SLIDER_Y_DIFF 2

#define CHECKBOX_W 12
#define CHECKBOX_H 12
#define CHECKBOX_Y_DIFF 2

#define INPUTBOX_LONG_W 180
#define INPUTBOX_SHORT_W 80
#define INPUTBOX_H 20
#define INPUTBOX_Y_DIFF -2

#define BUTTON_W 96
#define BUTTON_H 24
#define BUTTON_Y_DIFF -4

#define MSGBOX_W 224
#define MSGBOX_H 96

#define TEX_BOX_X 504
#define TEX_BOX_Y 8
#define TEX_BOX_SIZE 512

#define APP_NAME_LABEL_X PADDING
#define APP_NAME_LABEL_Y PADDING
#define APP_NAME_LABEL_W LABEL_W
#define APP_NAME_LABEL_H LABEL_H

#define EXPORT_FILENAME_LABEL "FILENAME:"
#define EXPORT_FILENAME_START_VAL "noise.png"
#define EXPORT_FILENAME_LABEL_X PADDING
#define EXPORT_FILENAME_LABEL_Y APP_NAME_LABEL_Y + V_SHORT_GAP
#define EXPORT_FILENAME_LABEL_W LABEL_W
#define EXPORT_FILENAME_LABEL_H LABEL_H
#define EXPORT_FILENAME_MAX_SIZE 64
#define EXPORT_FILENAME_X INPUT_START_X
#define EXPORT_FILENAME_Y EXPORT_FILENAME_LABEL_Y + INPUTBOX_Y_DIFF
#define EXPORT_FILENAME_W INPUTBOX_LONG_W
#define EXPORT_FILENAME_H INPUTBOX_H

#define EXPORT_BTN_LABEL "EXPORT"
#define EXPORT_BTN_X EXPORT_FILENAME_X + EXPORT_FILENAME_W + H_MEDIUM_GAP
#define EXPORT_BTN_Y EXPORT_FILENAME_LABEL_Y + BUTTON_Y_DIFF
#define EXPORT_BTN_W BUTTON_W
#define EXPORT_BTN_H BUTTON_H

#define RES_SELECTOR_LABEL "RESOLUTION:"
#define RES_SELECTOR_LABEL_X PADDING
#define RES_SELECTOR_LABEL_Y EXPORT_BTN_Y + V_SHORT_GAP
#define RES_SELECTOR_LABEL_W LABEL_W
#define RES_SELECTOR_LABEL_H LABEL_H
#define RES_SELECTOR_W INPUTBOX_SHORT_W
#define RES_SELECTOR_H INPUTBOX_H
#define RES_SELECTOR_X_X INPUT_START_X
#define RES_SELECTOR_X_Y RES_SELECTOR_LABEL_Y + INPUTBOX_Y_DIFF
#define RES_SELECTOR_Y_X RES_SELECTOR_X_X + RES_SELECTOR_W + H_SHORT_GAP
#define RES_SELECTOR_Y_Y RES_SELECTOR_LABEL_Y + INPUTBOX_Y_DIFF
#define RES_SELECTOR_MIN 1
#define RES_SELECTOR_MAX 4096
#define RES_SELECTOR_X_LABEL "X "
#define RES_SELECTOR_Y_LABEL "Y "

#define EXPORT_MSGBOX_SUCCESS_TITLE "Export image"
#define EXPORT_MSGBOX_SUCCESS_MESSAGE "Image exported successfully."
#define EXPORT_MSGBOX_SUCCESS_BUTTONS "Ok"
#define EXPORT_MSGBOX_SUCCESS_W MSGBOX_W
#define EXPORT_MSGBOX_SUCCESS_H MSGBOX_H
#define EXPORT_MSGBOX_FAILURE_TITLE "Export image"
#define EXPORT_MSGBOX_FAILURE_MESSAGE "Exporting image failed."
#define EXPORT_MSGBOX_FAILURE_BUTTONS "Ok"
#define EXPORT_MSGBOX_FAILURE_W MSGBOX_W
#define EXPORT_MSGBOX_FAILURE_H MSGBOX_H

#define NOISE_TYPE_LABEL "NOISE:"
#define NOISE_TYPE_LABEL_X PADDING
#define NOISE_TYPE_LABEL_Y RES_SELECTOR_LABEL_Y + V_LONG_GAP
#define NOISE_TYPE_LABEL_W LABEL_W
#define NOISE_TYPE_LABEL_H LABEL_H
#define NOISE_TYPE_X INPUT_START_X
#define NOISE_TYPE_Y NOISE_TYPE_LABEL_Y + BUTTON_Y_DIFF
#define NOISE_TYPE_W BUTTON_W
#define NOISE_TYPE_H BUTTON_H
#define NOISE_TYPE_OPTIONS "Open Simplex;Cellular"

#define CE_MODE_LABEL "MODE:"
#define CE_MODE_LABEL_X PADDING
#define CE_MODE_LABEL_Y NOISE_TYPE_LABEL_Y + V_LONG_GAP
#define CE_MODE_LABEL_W LABEL_W
#define CE_MODE_LABEL_H LABEL_H
#define CE_MODE_X INPUT_START_X
#define CE_MODE_Y CE_MODE_LABEL_Y + BUTTON_Y_DIFF
#define CE_MODE_W BUTTON_W
#define CE_MODE_H BUTTON_H
#define CE_MODE_OPTIONS "d1;d2 - d1"

#define CE_SQUARED_LABEL "SQUARED"
#define CE_SQUARED_X CE_MODE_X + CE_MODE_W * 2 + H_SHORT_GAP
#define CE_SQUARED_Y CE_MODE_LABEL_Y + CHECKBOX_Y_DIFF
#define CE_SQUARED_W CHECKBOX_W
#define CE_SQUARED_H CHECKBOX_H

#define OS_SEED_SELECTOR_LABEL "SEED:"
#define OS_SEED_SELECTOR_LABEL_X PADDING
#define OS_SEED_SELECTOR_LABEL_Y NOISE_TYPE_LABEL_Y + V_LONG_GAP
#define OS_SEED_SELECTOR_LABEL_W LABEL_W
#define OS_SEED_SELECTOR_LABEL_H LABEL_H
#define OS_SEED_SELECTOR_X INPUT_START_X
#define OS_SEED_SELECTOR_Y OS_SEED_SELECTOR_LABEL_Y + INPUTBOX_Y_DIFF
#define OS_SEED_SELECTOR_W INPUTBOX_LONG_W
#define OS_SEED_SELECTOR_H INPUTBOX_H
#define OS_SEED_SELECTOR_MIN -999999
#define OS_SEED_SELECTOR_MAX 999999

#define CE_SEED_SELECTOR_LABEL "SEED:"
#define CE_SEED_SELECTOR_LABEL_X PADDING
#define CE_SEED_SELECTOR_LABEL_Y CE_MODE_LABEL_Y + V_LONG_GAP
#define CE_SEED_SELECTOR_LABEL_W LABEL_W
#define CE_SEED_SELECTOR_LABEL_H LABEL_H
#define CE_SEED_SELECTOR_X INPUT_START_X
#define CE_SEED_SELECTOR_Y CE_SEED_SELECTOR_LABEL_Y + INPUTBOX_Y_DIFF
#define CE_SEED_SELECTOR_W INPUTBOX_LONG_W
#define CE_SEED_SELECTOR_H INPUTBOX_H
#define CE_SEED_SELECTOR_MIN -999999
#define CE_SEED_SELECTOR_MAX 999999

#define OS_FREQ_SELECTOR_LABEL "FREQUENCY:"
#define OS_FREQ_SELECTOR_LABEL_LEFT "0.0"
#define OS_FREQ_SELECTOR_LABEL_RIGHT "2.0"
#define OS_FREQ_SELECTOR_LABEL_X PADDING
#define OS_FREQ_SELECTOR_LABEL_Y OS_SEED_SELECTOR_LABEL_Y + V_SHORT_GAP
#define OS_FREQ_SELECTOR_LABEL_W LABEL_W
#define OS_FREQ_SELECTOR_LABEL_H LABEL_H
#define OS_FREQ_SELECTOR_X INPUT_START_X
#define OS_FREQ_SELECTOR_Y OS_FREQ_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define OS_FREQ_SELECTOR_W SLIDER_LONG_W
#define OS_FREQ_SELECTOR_H SLIDER_H
#define OS_FREQ_SELECTOR_MIN 0.00001f
#define OS_FREQ_SELECTOR_MAX 2.0f
#define OS_FREQ_SELECTOR_VALUE_X                                               \
    OS_FREQ_SELECTOR_X + OS_FREQ_SELECTOR_W + H_MEDIUM_GAP
#define OS_FREQ_SELECTOR_VALUE_Y OS_FREQ_SELECTOR_LABEL_Y
#define OS_FREQ_SELECTOR_VALUE_W LABEL_W
#define OS_FREQ_SELECTOR_VALUE_H LABEL_H

#define CE_FREQ_SELECTOR_LABEL "FREQUENCY:"
#define CE_FREQ_SELECTOR_LABEL_LEFT "0.0"
#define CE_FREQ_SELECTOR_LABEL_RIGHT "2.0"
#define CE_FREQ_SELECTOR_LABEL_X PADDING
#define CE_FREQ_SELECTOR_LABEL_Y CE_SEED_SELECTOR_LABEL_Y + V_SHORT_GAP
#define CE_FREQ_SELECTOR_LABEL_W LABEL_W
#define CE_FREQ_SELECTOR_LABEL_H LABEL_H
#define CE_FREQ_SELECTOR_X INPUT_START_X
#define CE_FREQ_SELECTOR_Y CE_FREQ_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define CE_FREQ_SELECTOR_W SLIDER_LONG_W
#define CE_FREQ_SELECTOR_H SLIDER_H
#define CE_FREQ_SELECTOR_MIN 0.00001f
#define CE_FREQ_SELECTOR_MAX 2.0f
#define CE_FREQ_SELECTOR_VALUE_X                                               \
    CE_FREQ_SELECTOR_X + CE_FREQ_SELECTOR_W + H_MEDIUM_GAP
#define CE_FREQ_SELECTOR_VALUE_Y CE_FREQ_SELECTOR_LABEL_Y
#define CE_FREQ_SELECTOR_VALUE_W LABEL_W
#define CE_FREQ_SELECTOR_VALUE_H LABEL_H

#define OS_SEAMLESS_SELECTOR_LABEL "SEAMLESS"
#define OS_SEAMLESS_SELECTOR_X                                                 \
    OS_FREQ_SELECTOR_X + OS_FREQ_SELECTOR_W + H_XLONG_GAP
#define OS_SEAMLESS_SELECTOR_Y OS_FREQ_SELECTOR_LABEL_Y + CHECKBOX_Y_DIFF
#define OS_SEAMLESS_SELECTOR_W CHECKBOX_W
#define OS_SEAMLESS_SELECTOR_H CHECKBOX_H

#define CE_SEAMLESS_SELECTOR_LABEL "SEAMLESS"
#define CE_SEAMLESS_SELECTOR_X                                                 \
    CE_FREQ_SELECTOR_X + CE_FREQ_SELECTOR_W + H_XLONG_GAP
#define CE_SEAMLESS_SELECTOR_Y CE_FREQ_SELECTOR_LABEL_Y + CHECKBOX_Y_DIFF
#define CE_SEAMLESS_SELECTOR_W CHECKBOX_W
#define CE_SEAMLESS_SELECTOR_H CHECKBOX_H

#define CE_JITTER_SELECTOR_LABEL "JITTER:"
#define CE_JITTER_SELECTOR_LABEL_LEFT "0.0"
#define CE_JITTER_SELECTOR_LABEL_RIGHT "1.0"
#define CE_JITTER_SELECTOR_LABEL_X PADDING
#define CE_JITTER_SELECTOR_LABEL_Y CE_FREQ_SELECTOR_LABEL_Y + V_SHORT_GAP
#define CE_JITTER_SELECTOR_LABEL_W LABEL_W
#define CE_JITTER_SELECTOR_LABEL_H LABEL_H
#define CE_JITTER_SELECTOR_X INPUT_START_X
#define CE_JITTER_SELECTOR_Y CE_JITTER_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define CE_JITTER_SELECTOR_W SLIDER_LONG_W
#define CE_JITTER_SELECTOR_H SLIDER_H
#define CE_JITTER_SELECTOR_MIN 0.0f
#define CE_JITTER_SELECTOR_MAX 1.0f
#define CE_JITTER_SELECTOR_VALUE_X                                             \
    CE_JITTER_SELECTOR_X + CE_JITTER_SELECTOR_W + H_MEDIUM_GAP
#define CE_JITTER_SELECTOR_VALUE_Y CE_JITTER_SELECTOR_LABEL_Y
#define CE_JITTER_SELECTOR_VALUE_W LABEL_W
#define CE_JITTER_SELECTOR_VALUE_H LABEL_H

#define OS_POWER_SELECTOR_LABEL "POWER:"
#define OS_POWER_SELECTOR_LABEL_LEFT "1.0"
#define OS_POWER_SELECTOR_LABEL_RIGHT "8.0"
#define OS_POWER_SELECTOR_LABEL_X PADDING
#define OS_POWER_SELECTOR_LABEL_Y OS_FREQ_SELECTOR_LABEL_Y + V_SHORT_GAP
#define OS_POWER_SELECTOR_LABEL_W LABEL_W
#define OS_POWER_SELECTOR_LABEL_H LABEL_H
#define OS_POWER_SELECTOR_X INPUT_START_X
#define OS_POWER_SELECTOR_Y OS_POWER_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define OS_POWER_SELECTOR_W SLIDER_LONG_W
#define OS_POWER_SELECTOR_H SLIDER_H
#define OS_POWER_SELECTOR_MIN 1.0f
#define OS_POWER_SELECTOR_MAX 8.0f
#define OS_POWER_SELECTOR_VALUE_X                                              \
    OS_POWER_SELECTOR_X + OS_POWER_SELECTOR_W + H_MEDIUM_GAP
#define OS_POWER_SELECTOR_VALUE_Y OS_POWER_SELECTOR_LABEL_Y
#define OS_POWER_SELECTOR_VALUE_W LABEL_W
#define OS_POWER_SELECTOR_VALUE_H LABEL_H

#define CE_POWER_SELECTOR_LABEL "POWER:"
#define CE_POWER_SELECTOR_LABEL_LEFT "1.0"
#define CE_POWER_SELECTOR_LABEL_RIGHT "8.0"
#define CE_POWER_SELECTOR_LABEL_X PADDING
#define CE_POWER_SELECTOR_LABEL_Y CE_JITTER_SELECTOR_LABEL_Y + V_SHORT_GAP
#define CE_POWER_SELECTOR_LABEL_W LABEL_W
#define CE_POWER_SELECTOR_LABEL_H LABEL_H
#define CE_POWER_SELECTOR_X INPUT_START_X
#define CE_POWER_SELECTOR_Y CE_POWER_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define CE_POWER_SELECTOR_W SLIDER_LONG_W
#define CE_POWER_SELECTOR_H SLIDER_H
#define CE_POWER_SELECTOR_MIN 1.0f
#define CE_POWER_SELECTOR_MAX 8.0f
#define CE_POWER_SELECTOR_VALUE_X                                              \
    CE_POWER_SELECTOR_X + CE_POWER_SELECTOR_W + H_MEDIUM_GAP
#define CE_POWER_SELECTOR_VALUE_Y CE_POWER_SELECTOR_LABEL_Y
#define CE_POWER_SELECTOR_VALUE_W LABEL_W
#define CE_POWER_SELECTOR_VALUE_H LABEL_H

#define OS_INVERT_SELECTOR_LABEL "INVERT"
#define OS_INVERT_SELECTOR_X                                                   \
    OS_POWER_SELECTOR_X + OS_POWER_SELECTOR_W + H_XLONG_GAP
#define OS_INVERT_SELECTOR_Y OS_POWER_SELECTOR_LABEL_Y + CHECKBOX_Y_DIFF
#define OS_INVERT_SELECTOR_W CHECKBOX_W
#define OS_INVERT_SELECTOR_H CHECKBOX_H

#define CE_INVERT_SELECTOR_LABEL "INVERT"
#define CE_INVERT_SELECTOR_X                                                   \
    CE_POWER_SELECTOR_X + CE_POWER_SELECTOR_W + H_XLONG_GAP
#define CE_INVERT_SELECTOR_Y CE_POWER_SELECTOR_LABEL_Y + CHECKBOX_Y_DIFF
#define CE_INVERT_SELECTOR_W CHECKBOX_W
#define CE_INVERT_SELECTOR_H CHECKBOX_H

#define OS_RANGE_SELECTOR_LABEL "RANGE:"
#define OS_RANGE_SELECTOR_LABEL_X PADDING
#define OS_RANGE_SELECTOR_LABEL_Y OS_POWER_SELECTOR_LABEL_Y + V_SHORT_GAP
#define OS_RANGE_SELECTOR_LABEL_W LABEL_W
#define OS_RANGE_SELECTOR_LABEL_H LABEL_H
#define OS_RANGE_SELECTOR_MIN_LABEL "MIN "
#define OS_RANGE_SELECTOR_MIN_X INPUT_START_X
#define OS_RANGE_SELECTOR_MIN_Y OS_RANGE_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define OS_RANGE_SELECTOR_MIN_W SLIDER_SHORT_W
#define OS_RANGE_SELECTOR_MIN_H SLIDER_H
#define OS_RANGE_SELECTOR_MIN_MIN -1.0f
#define OS_RANGE_SELECTOR_MIN_MAX 1.0f
#define OS_RANGE_SELECTOR_MAX_LABEL " MAX"
#define OS_RANGE_SELECTOR_MAX_X                                                \
    OS_RANGE_SELECTOR_MIN_X + OS_RANGE_SELECTOR_MIN_W + H_LONG_GAP
#define OS_RANGE_SELECTOR_MAX_Y OS_RANGE_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define OS_RANGE_SELECTOR_MAX_W SLIDER_SHORT_W
#define OS_RANGE_SELECTOR_MAX_H SLIDER_H
#define OS_RANGE_SELECTOR_MAX_MIN -1.0f
#define OS_RANGE_SELECTOR_MAX_MAX 1.0f

#define CE_RANGE_SELECTOR_LABEL "RANGE:"
#define CE_RANGE_SELECTOR_LABEL_X PADDING
#define CE_RANGE_SELECTOR_LABEL_Y CE_POWER_SELECTOR_LABEL_Y + V_SHORT_GAP
#define CE_RANGE_SELECTOR_LABEL_W LABEL_W
#define CE_RANGE_SELECTOR_LABEL_H LABEL_H
#define CE_RANGE_SELECTOR_MIN_LABEL "MIN "
#define CE_RANGE_SELECTOR_MIN_X INPUT_START_X
#define CE_RANGE_SELECTOR_MIN_Y CE_RANGE_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define CE_RANGE_SELECTOR_MIN_W SLIDER_SHORT_W
#define CE_RANGE_SELECTOR_MIN_H SLIDER_H
#define CE_RANGE_SELECTOR_MIN_MIN -1.0f
#define CE_RANGE_SELECTOR_MIN_MAX 1.0f
#define CE_RANGE_SELECTOR_MAX_LABEL " MAX"
#define CE_RANGE_SELECTOR_MAX_X                                                \
    CE_RANGE_SELECTOR_MIN_X + CE_RANGE_SELECTOR_MIN_W + H_LONG_GAP
#define CE_RANGE_SELECTOR_MAX_Y CE_RANGE_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define CE_RANGE_SELECTOR_MAX_W SLIDER_SHORT_W
#define CE_RANGE_SELECTOR_MAX_H SLIDER_H
#define CE_RANGE_SELECTOR_MAX_MIN -1.0f
#define CE_RANGE_SELECTOR_MAX_MAX 1.0f

#define OS_OCTAVES_SELECTOR_LABEL "OCTAVES:"
#define OS_OCTAVES_SELECTOR_LABEL_LEFT "1"
#define OS_OCTAVES_SELECTOR_LABEL_RIGHT "8"
#define OS_OCTAVES_SELECTOR_LABEL_X PADDING
#define OS_OCTAVES_SELECTOR_LABEL_Y OS_RANGE_SELECTOR_LABEL_Y + V_LONG_GAP
#define OS_OCTAVES_SELECTOR_LABEL_W LABEL_W
#define OS_OCTAVES_SELECTOR_LABEL_H LABEL_H
#define OS_OCTAVES_SELECTOR_X INPUT_START_X
#define OS_OCTAVES_SELECTOR_Y OS_OCTAVES_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define OS_OCTAVES_SELECTOR_W SLIDER_LONG_W
#define OS_OCTAVES_SELECTOR_H SLIDER_H
#define OS_OCTAVES_SELECTOR_MIN 1.0f
#define OS_OCTAVES_SELECTOR_MAX 8.0f
#define OS_OCTAVES_SELECTOR_VALUE_X                                            \
    OS_OCTAVES_SELECTOR_X + OS_OCTAVES_SELECTOR_W + H_MEDIUM_GAP
#define OS_OCTAVES_SELECTOR_VALUE_Y OS_OCTAVES_SELECTOR_LABEL_Y
#define OS_OCTAVES_SELECTOR_VALUE_W LABEL_W
#define OS_OCTAVES_SELECTOR_VALUE_H LABEL_H

#define CE_OCTAVES_SELECTOR_LABEL "OCTAVES:"
#define CE_OCTAVES_SELECTOR_LABEL_LEFT "1"
#define CE_OCTAVES_SELECTOR_LABEL_RIGHT "8"
#define CE_OCTAVES_SELECTOR_LABEL_X PADDING
#define CE_OCTAVES_SELECTOR_LABEL_Y CE_RANGE_SELECTOR_LABEL_Y + V_LONG_GAP
#define CE_OCTAVES_SELECTOR_LABEL_W LABEL_W
#define CE_OCTAVES_SELECTOR_LABEL_H LABEL_H
#define CE_OCTAVES_SELECTOR_X INPUT_START_X
#define CE_OCTAVES_SELECTOR_Y CE_OCTAVES_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define CE_OCTAVES_SELECTOR_W SLIDER_LONG_W
#define CE_OCTAVES_SELECTOR_H SLIDER_H
#define CE_OCTAVES_SELECTOR_MIN 1.0f
#define CE_OCTAVES_SELECTOR_MAX 8.0f
#define CE_OCTAVES_SELECTOR_VALUE_X                                            \
    CE_OCTAVES_SELECTOR_X + CE_OCTAVES_SELECTOR_W + H_MEDIUM_GAP
#define CE_OCTAVES_SELECTOR_VALUE_Y CE_OCTAVES_SELECTOR_LABEL_Y
#define CE_OCTAVES_SELECTOR_VALUE_W LABEL_W
#define CE_OCTAVES_SELECTOR_VALUE_H LABEL_H

#define OS_PERSISTENCE_SELECTOR_LABEL "PERSISTENCE:"
#define OS_PERSISTENCE_SELECTOR_LABEL_LEFT "0.0"
#define OS_PERSISTENCE_SELECTOR_LABEL_RIGHT "1.0"
#define OS_PERSISTENCE_SELECTOR_LABEL_X PADDING
#define OS_PERSISTENCE_SELECTOR_LABEL_Y                                        \
    OS_OCTAVES_SELECTOR_LABEL_Y + V_SHORT_GAP
#define OS_PERSISTENCE_SELECTOR_LABEL_W LABEL_W
#define OS_PERSISTENCE_SELECTOR_LABEL_H LABEL_H
#define OS_PERSISTENCE_SELECTOR_X INPUT_START_X
#define OS_PERSISTENCE_SELECTOR_Y                                              \
    OS_PERSISTENCE_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define OS_PERSISTENCE_SELECTOR_W SLIDER_LONG_W
#define OS_PERSISTENCE_SELECTOR_H SLIDER_H
#define OS_PERSISTENCE_SELECTOR_MIN 0.0f
#define OS_PERSISTENCE_SELECTOR_MAX 1.0f
#define OS_PERSISTENCE_SELECTOR_VALUE_X                                        \
    OS_PERSISTENCE_SELECTOR_X + OS_PERSISTENCE_SELECTOR_W + H_MEDIUM_GAP
#define OS_PERSISTENCE_SELECTOR_VALUE_Y OS_PERSISTENCE_SELECTOR_LABEL_Y
#define OS_PERSISTENCE_SELECTOR_VALUE_W LABEL_W
#define OS_PERSISTENCE_SELECTOR_VALUE_H LABEL_H

#define CE_PERSISTENCE_SELECTOR_LABEL "PERSISTENCE:"
#define CE_PERSISTENCE_SELECTOR_LABEL_LEFT "0.0"
#define CE_PERSISTENCE_SELECTOR_LABEL_RIGHT "1.0"
#define CE_PERSISTENCE_SELECTOR_LABEL_X PADDING
#define CE_PERSISTENCE_SELECTOR_LABEL_Y                                        \
    CE_OCTAVES_SELECTOR_LABEL_Y + V_SHORT_GAP
#define CE_PERSISTENCE_SELECTOR_LABEL_W LABEL_W
#define CE_PERSISTENCE_SELECTOR_LABEL_H LABEL_H
#define CE_PERSISTENCE_SELECTOR_X INPUT_START_X
#define CE_PERSISTENCE_SELECTOR_Y                                              \
    CE_PERSISTENCE_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define CE_PERSISTENCE_SELECTOR_W SLIDER_LONG_W
#define CE_PERSISTENCE_SELECTOR_H SLIDER_H
#define CE_PERSISTENCE_SELECTOR_MIN 0.0f
#define CE_PERSISTENCE_SELECTOR_MAX 1.0f
#define CE_PERSISTENCE_SELECTOR_VALUE_X                                        \
    CE_PERSISTENCE_SELECTOR_X + CE_PERSISTENCE_SELECTOR_W + H_MEDIUM_GAP
#define CE_PERSISTENCE_SELECTOR_VALUE_Y CE_PERSISTENCE_SELECTOR_LABEL_Y
#define CE_PERSISTENCE_SELECTOR_VALUE_W LABEL_W
#define CE_PERSISTENCE_SELECTOR_VALUE_H LABEL_H

#define OS_LACUNARITY_SELECTOR_LABEL "LACUNARITY:"
#define OS_LACUNARITY_SELECTOR_LABEL_LEFT "0.1"
#define OS_LACUNARITY_SELECTOR_LABEL_RIGHT "4.0"
#define OS_LACUNARITY_SELECTOR_LABEL_X PADDING
#define OS_LACUNARITY_SELECTOR_LABEL_Y                                         \
    OS_PERSISTENCE_SELECTOR_LABEL_Y + V_SHORT_GAP
#define OS_LACUNARITY_SELECTOR_LABEL_W LABEL_W
#define OS_LACUNARITY_SELECTOR_LABEL_H LABEL_H
#define OS_LACUNARITY_SELECTOR_X INPUT_START_X
#define OS_LACUNARITY_SELECTOR_Y OS_LACUNARITY_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define OS_LACUNARITY_SELECTOR_W SLIDER_LONG_W
#define OS_LACUNARITY_SELECTOR_H SLIDER_H
#define OS_LACUNARITY_SELECTOR_MIN 0.1f
#define OS_LACUNARITY_SELECTOR_MAX 4.0f
#define OS_LACUNARITY_SELECTOR_VALUE_X                                         \
    OS_LACUNARITY_SELECTOR_X + OS_LACUNARITY_SELECTOR_W + H_MEDIUM_GAP
#define OS_LACUNARITY_SELECTOR_VALUE_Y OS_LACUNARITY_SELECTOR_LABEL_Y
#define OS_LACUNARITY_SELECTOR_VALUE_W LABEL_W
#define OS_LACUNARITY_SELECTOR_VALUE_H LABEL_H

#define CE_LACUNARITY_SELECTOR_LABEL "LACUNARITY:"
#define CE_LACUNARITY_SELECTOR_LABEL_LEFT "0.1"
#define CE_LACUNARITY_SELECTOR_LABEL_RIGHT "4.0"
#define CE_LACUNARITY_SELECTOR_LABEL_X PADDING
#define CE_LACUNARITY_SELECTOR_LABEL_Y                                         \
    CE_PERSISTENCE_SELECTOR_LABEL_Y + V_SHORT_GAP
#define CE_LACUNARITY_SELECTOR_LABEL_W LABEL_W
#define CE_LACUNARITY_SELECTOR_LABEL_H LABEL_H
#define CE_LACUNARITY_SELECTOR_X INPUT_START_X
#define CE_LACUNARITY_SELECTOR_Y CE_LACUNARITY_SELECTOR_LABEL_Y + SLIDER_Y_DIFF
#define CE_LACUNARITY_SELECTOR_W SLIDER_LONG_W
#define CE_LACUNARITY_SELECTOR_H SLIDER_H
#define CE_LACUNARITY_SELECTOR_MIN 0.1f
#define CE_LACUNARITY_SELECTOR_MAX 4.0f
#define CE_LACUNARITY_SELECTOR_VALUE_X                                         \
    CE_LACUNARITY_SELECTOR_X + CE_LACUNARITY_SELECTOR_W + H_MEDIUM_GAP
#define CE_LACUNARITY_SELECTOR_VALUE_Y CE_LACUNARITY_SELECTOR_LABEL_Y
#define CE_LACUNARITY_SELECTOR_VALUE_W LABEL_W
#define CE_LACUNARITY_SELECTOR_VALUE_H LABEL_H
